/** Part 4 talk grammar — second set of kits (novelty capacity). */
import type { DistractorType } from '../../domain/types';
import type { TalkKit, TOpt } from './part4Talks';

const o = (text: string, type: DistractorType): TOpt => ({ text, type });

// ===========================================================================
const advertisement: TalkKit = {
  id: 'ad',
  type: 'broadcast',
  title: 'Advertisement',
  instances: [
    { sit: 'retail', f: { biz: 'Summit Outdoor Gear', thing: 'our spring camping collection', gen: 'outdoor equipment', where: 'any of our five stores' }, role: 'An advertiser', place: 'On the radio' },
    { sit: 'technology', f: { biz: 'Cobalt Electronics', thing: 'our new line of noise-canceling headphones', gen: 'electronic devices', where: 'our website' }, role: 'An advertiser', place: 'On the radio' },
    { sit: 'restaurant', f: { biz: 'Greenfield Catering', thing: 'our office lunch delivery service', gen: 'a food service', where: 'our mobile app' }, role: 'An advertiser', place: 'On the radio' },
    { sit: 'banking', f: { biz: 'Meridian Financial', thing: 'our small-business accounts', gen: 'a banking service', where: 'any Meridian branch' }, role: 'An advertiser', place: 'On the radio' },
  ],
  opening: {
    1: [(v) => `Looking for something new? ${v.i.f.biz} is proud to introduce ${v.i.f.thing}.`],
    2: [(v) => `Tired of waiting and paying too much? You're not alone — and that's exactly why ${v.i.f.biz} created ${v.i.f.thing}.`],
    3: [(v) => `Picture this: it's Monday morning, the coffee machine is broken, and your first meeting starts in ten minutes. At ${v.i.f.biz}, we think about moments like that — which brings us to ${v.i.f.thing}.`],
  },
  detail: (v) => `Everything is available now at ${v.i.f.where}.`,
  detailQ: (v) => ({ stem: 'Where can listeners get the product or service?', answer: `At ${v.i.f.where}`, d: [o('Only by telephone', 'reasonable_but_unstated'), o('At a trade show', 'reasonable_but_unstated'), o('Through a catalog', 'reasonable_but_unstated')] }),
  purposeStem: 'What is being advertised?',
  purpose: (v) => v.i.f.gen.charAt(0).toUpperCase() + v.i.f.gen.slice(1),
  purposeD: () => [o('A coffee machine', 'true_but_irrelevant'), o('A job opening', 'reasonable_but_unstated'), o('A training course', 'reasonable_but_unstated'), o('A travel package', 'reasonable_but_unstated')],
  roleStem: 'Where would the talk most likely be heard?',
  turns: [
    {
      id: 'first_hundred',
      setup: () => 'And for this month only, there is a special offer.',
      line: () => 'The first hundred customers get a second item free — and last time, that took less than a day.',
      why: () => 'To encourage listeners to act quickly',
      whyD: () => [o('To report sales figures', 'literal_interpretation'), o('To apologize for a shortage', 'reasonable_but_unstated'), o('To announce a price increase', 'opposite_meaning')],
      implies: () => 'The offer is likely to run out soon.',
      impliesD: () => [o('The offer lasts all year.', 'opposite_meaning'), o('Only one hundred items were made.', 'keyword_overlap'), o('The last promotion failed.', 'opposite_meaning')],
      indirect: 2,
      follow: () => "So don't wait.",
      request: () => 'Visit us today, and mention this ad at checkout.',
      reqStem: 'What are listeners asked to do at checkout?',
      reqAnswer: () => 'Mention an advertisement',
      reqD: () => [o('Show a membership card', 'reasonable_but_unstated'), o('Fill out a survey', 'reasonable_but_unstated'), o('Pay in cash', 'reasonable_but_unstated')],
      problem: () => 'A promotion is limited.',
      problemD: () => [o('A product was recalled.', 'reasonable_but_unstated'), o('A store has closed.', 'reasonable_but_unstated'), o('Prices have increased.', 'reasonable_but_unstated')],
    },
    {
      id: 'no_contract',
      setup: () => 'We know that signing long contracts can feel risky.',
      line: () => "That's why you can cancel anytime — no questions asked.",
      why: () => 'To reduce customers\' concerns about commitment',
      whyD: () => [o('To explain how to cancel an order', 'literal_interpretation'), o('To announce the end of a service', 'reasonable_but_unstated'), o('To describe a new contract', 'opposite_meaning')],
      implies: () => 'Customers are not locked into a long agreement.',
      impliesD: () => [o('Cancellation requires a fee.', 'opposite_meaning'), o('Customers must sign for two years.', 'opposite_meaning'), o('The company rarely answers questions.', 'keyword_overlap')],
      indirect: 2,
      follow: () => 'We think you will want to stay anyway.',
      request: () => 'Sign up online and get your first month at half price.',
      reqStem: 'What is offered to new customers?',
      reqAnswer: () => 'A discount on the first month',
      reqD: () => [o('A free gift', 'reasonable_but_unstated'), o('Free delivery for a year', 'reasonable_but_unstated'), o('A longer contract', 'opposite_meaning')],
      problem: () => 'Customers may worry about long commitments.',
      problemD: () => [o('Customers find the product too heavy.', 'reasonable_but_unstated'), o('Customers cannot find the store.', 'reasonable_but_unstated'), o('The service is often late.', 'reasonable_but_unstated')],
    },
    {
      id: 'award',
      setup: () => "Don't just take our word for it.",
      line: () => 'Our customers have voted us number one in the region three years in a row.',
      why: () => 'To show that the company is trusted',
      whyD: () => [o('To announce a voting event', 'literal_interpretation'), o('To celebrate an anniversary', 'reasonable_but_unstated'), o('To introduce a new region', 'keyword_overlap')],
      implies: () => 'The company has a strong reputation.',
      impliesD: () => [o('The company is new.', 'opposite_meaning'), o('Customers must vote to receive a discount.', 'keyword_overlap'), o('The company only operates for three years.', 'reasonable_but_unstated')],
      indirect: 1,
      follow: () => 'Come and see why.',
      request: () => 'Call us today to book a free consultation.',
      reqStem: 'What does the speaker invite listeners to do?',
      reqAnswer: () => 'Arrange a free consultation',
      reqD: () => [o('Vote in a contest', 'keyword_overlap'), o('Download a coupon', 'reasonable_but_unstated'), o('Attend an award ceremony', 'reasonable_but_unstated')],
      problem: () => 'Listeners may doubt the company\'s claims.',
      problemD: () => [o('The company has lost customers.', 'opposite_meaning'), o('The phone lines are busy.', 'reasonable_but_unstated'), o('The product is out of stock.', 'reasonable_but_unstated')],
    },
  ],
};

// ===========================================================================
const orientation: TalkKit = {
  id: 'orientation',
  type: 'workshop',
  title: 'Talk',
  instances: [
    { sit: 'hr', f: { org: 'Harlow Logistics', group: 'new employees', purpose: 'To welcome new employees' }, role: 'A human resources manager', place: 'At a company orientation' },
    { sit: 'retail', f: { org: 'Everly Furniture', group: 'seasonal sales staff', purpose: 'To prepare new staff members' }, role: 'A store manager', place: 'At a store' },
    { sit: 'events', f: { org: 'the Lakeview Home Show', group: 'volunteers', purpose: 'To give instructions to volunteers' }, role: 'An event coordinator', place: 'At an event' },
    { sit: 'hotel', f: { org: 'Pinecrest Hotels', group: 'new front desk staff', purpose: 'To prepare new staff members' }, role: 'A hotel manager', place: 'At a hotel' },
  ],
  opening: {
    1: [(v) => `Good morning, and welcome to ${v.i.f.org}. This session is for all ${v.i.f.group}.`],
    2: [(v) => `Good morning, everyone. I know some of you had an early start, so thank you for being here. Let's get you ready for your first week at ${v.i.f.org}.`],
    3: [(v) => `Morning, everyone. Five years ago, I was sitting exactly where you are now, just as nervous. So, let me tell you what I wish someone had told me on my first day at ${v.i.f.org}.`],
  },
  detail: () => 'Your ID badges will be ready at the front desk after lunch.',
  detailQ: () => ({ stem: 'When will the ID badges be ready?', answer: 'After lunch', d: [o('Before the session', 'wrong_time'), o('At the end of the week', 'reasonable_but_unstated'), o('Tomorrow morning', 'reasonable_but_unstated')] }),
  purposeStem: 'What is the purpose of the talk?',
  purpose: (v) => v.i.f.purpose,
  purposeD: () => [o('To announce a promotion', 'reasonable_but_unstated'), o('To describe the speaker\'s career', 'true_but_irrelevant'), o('To introduce a new product', 'reasonable_but_unstated'), o('To explain a schedule change', 'reasonable_but_unstated')],
  roleStem: 'Who most likely is the speaker?',
  turns: [
    {
      id: 'shadow',
      setup: () => "Now, I know there's a lot to remember.",
      line: () => 'Nobody expects you to know everything by Friday.',
      why: () => 'To reassure the listeners',
      whyD: () => [o('To set a deadline', 'opposite_meaning'), o('To describe the weekly schedule', 'literal_interpretation'), o('To criticize previous employees', 'reasonable_but_unstated')],
      implies: () => 'The listeners will have time to learn.',
      impliesD: () => [o('A test will be held on Friday.', 'keyword_overlap'), o('The listeners must work on Friday.', 'reasonable_but_unstated'), o('The training ends early.', 'reasonable_but_unstated')],
      indirect: 2,
      follow: () => "For your first two weeks, you'll each work alongside an experienced colleague.",
      request: () => 'Please find the name of your partner on the sheet in your folder.',
      reqStem: 'What are the listeners asked to do?',
      reqAnswer: () => 'Look for a name in a folder',
      reqD: () => [o('Pick up a badge now', 'wrong_time'), o('Sign a contract', 'reasonable_but_unstated'), o('Introduce themselves', 'reasonable_but_unstated')],
      problem: () => 'There is a lot of information to learn.',
      problemD: () => [o('Some badges are missing.', 'reasonable_but_unstated'), o('The session started late.', 'reasonable_but_unstated'), o('There are not enough folders.', 'keyword_overlap')],
    },
    {
      id: 'parking',
      setup: () => 'One practical thing before we continue.',
      line: () => 'The main parking lot is usually full by eight-fifteen.',
      why: () => 'To advise the listeners to arrive early',
      whyD: () => [o('To complain about the parking lot', 'reasonable_but_unstated'), o('To report the size of the parking lot', 'literal_interpretation'), o('To announce a new parking fee', 'reasonable_but_unstated')],
      implies: () => 'Arriving late may make parking difficult.',
      impliesD: () => [o('The lot is closed after eight.', 'reasonable_but_unstated'), o('Employees must take the bus.', 'reasonable_but_unstated'), o('Parking is always easy to find.', 'opposite_meaning')],
      indirect: 2,
      follow: () => 'There is overflow parking behind the warehouse, but it is a ten-minute walk.',
      request: () => "Now, let's take a quick tour of the building.",
      reqStem: 'What will the listeners most likely do next?',
      reqAnswer: () => 'Tour the building',
      reqD: () => [o('Move their cars', 'keyword_overlap'), o('Eat lunch', 'reasonable_but_unstated'), o('Meet their partners', 'reasonable_but_unstated')],
      problem: () => 'Parking fills up early.',
      problemD: () => [o('The warehouse is closed.', 'keyword_overlap'), o('The building is being renovated.', 'reasonable_but_unstated'), o('The tour was canceled.', 'reasonable_but_unstated')],
    },
    {
      id: 'questions_hr',
      setup: () => 'You will get a lot of forms this week.',
      line: (v) => `${v.third.first} in our office has answered every question you could possibly think of.`,
      why: (v) => `To recommend ${v.third.first} as a source of help`,
      whyD: (v) => [o(`To introduce ${v.third.first} as a new employee`, 'reasonable_but_unstated'), o(`To praise ${v.third.first}'s long career`, 'literal_interpretation'), o('To warn about difficult questions', 'opposite_meaning')],
      implies: (v) => `Listeners should go to ${v.third.first} with any questions.`,
      impliesD: (v) => [o(`${v.third.first} is very busy.`, 'opposite_meaning'), o(`${v.third.first} will lead the tour.`, 'reasonable_but_unstated'), o('There will be a test.', 'reasonable_but_unstated')],
      indirect: 3,
      follow: () => 'Our office is on the second floor, right next to the elevators.',
      request: () => 'Please return the signed forms by Wednesday.',
      reqStem: 'What must the listeners do by Wednesday?',
      reqAnswer: () => 'Submit some documents',
      reqD: () => [o('Visit the second floor', 'keyword_overlap'), o('Choose a parking space', 'reasonable_but_unstated'), o('Complete a training course', 'reasonable_but_unstated')],
      problem: () => 'New employees will have many forms to complete.',
      problemD: () => [o('The elevators are out of order.', 'keyword_overlap'), o('The office has moved.', 'reasonable_but_unstated'), o('Some forms were lost.', 'reasonable_but_unstated')],
    },
  ],
};

// ===========================================================================
const recorded: TalkKit = {
  id: 'recorded',
  type: 'voicemail',
  title: 'Recorded message',
  instances: [
    { sit: 'customer_service', f: { biz: 'Cobalt Electronics customer support', gen: 'a customer support line' }, role: 'A recorded message', place: 'On a telephone line' },
    { sit: 'banking', f: { biz: 'Meridian Financial', gen: 'a bank' }, role: 'A recorded message', place: 'On a telephone line' },
    { sit: 'maintenance', f: { biz: 'Ridgeview Property Maintenance', gen: 'a maintenance company' }, role: 'A recorded message', place: 'On a telephone line' },
    { sit: 'travel', f: { biz: 'Kestrel Airlines reservations', gen: 'an airline' }, role: 'A recorded message', place: 'On a telephone line' },
  ],
  opening: {
    1: [(v) => `Thank you for calling ${v.i.f.biz}. Our office is currently closed.`],
    2: [(v) => `You've reached ${v.i.f.biz}. We're sorry we can't take your call right now — our regular hours are eight to six, Monday through Friday.`],
    3: [(v) => `Hello, and thank you for calling ${v.i.f.biz}. We've recently updated our phone system, so please listen carefully, as some options have changed.`],
  },
  detail: () => 'Our team will return all messages by noon the next business day.',
  detailQ: () => ({ stem: 'When will messages be returned?', answer: 'By noon the next business day', d: [o('Within an hour', 'reasonable_but_unstated'), o('At the end of the week', 'reasonable_but_unstated'), o('After six o\'clock', 'wrong_time')] }),
  purposeStem: 'What is the purpose of the message?',
  purpose: () => 'To provide information to callers',
  purposeD: () => [o('To advertise a new phone', 'keyword_overlap'), o('To announce a job opening', 'reasonable_but_unstated'), o('To confirm an appointment', 'reasonable_but_unstated'), o('To apologize for a billing error', 'reasonable_but_unstated')],
  roleStem: 'Where would listeners most likely hear this message?',
  turns: [
    {
      id: 'website_faster',
      setup: () => 'We are receiving more calls than usual this week.',
      line: () => 'Most questions can be answered on our website in under two minutes.',
      why: () => 'To suggest a faster way to get help',
      whyD: () => [o('To advertise a new website design', 'literal_interpretation'), o('To say that the website is down', 'opposite_meaning'), o('To limit the length of calls', 'keyword_overlap')],
      implies: () => 'Callers may not need to wait for an agent.',
      impliesD: () => [o('The website is difficult to use.', 'opposite_meaning'), o('All calls last two minutes.', 'keyword_overlap'), o('Callers must visit in person.', 'reasonable_but_unstated')],
      indirect: 2,
      follow: () => 'You can also chat with an assistant online at any time.',
      request: () => 'To leave a message, please press one now.',
      reqStem: 'What should callers do to leave a message?',
      reqAnswer: () => 'Press a number',
      reqD: () => [o('Visit the website', 'true_but_irrelevant'), o('Call back later', 'reasonable_but_unstated'), o('Send an e-mail', 'reasonable_but_unstated')],
      problem: () => 'Call volume is higher than normal.',
      problemD: () => [o('The phone system is broken.', 'reasonable_but_unstated'), o('The office has moved.', 'reasonable_but_unstated'), o('The website is being updated.', 'reasonable_but_unstated')],
    },
    {
      id: 'emergency',
      setup: () => 'If your call is about a routine matter, please stay on the line.',
      line: () => 'If water is leaking or you smell gas, however, do not wait for our office to open.',
      why: () => 'To explain what to do in urgent situations',
      whyD: () => [o('To describe common repairs', 'literal_interpretation'), o('To announce a gas price change', 'keyword_overlap'), o('To say that the office opens early', 'reasonable_but_unstated')],
      implies: () => 'Urgent problems require immediate action.',
      impliesD: () => [o('All problems can wait until morning.', 'opposite_meaning'), o('The office handles only water problems.', 'reasonable_but_unstated'), o('Callers should open a window.', 'reasonable_but_unstated')],
      indirect: 1,
      follow: () => 'Instead, call our twenty-four-hour line at 555-0147.',
      request: () => 'For all other questions, please leave your name and number after the tone.',
      reqStem: 'What are callers with routine questions asked to do?',
      reqAnswer: () => 'Leave their contact information',
      reqD: () => [o('Call a twenty-four-hour line', 'wrong_person'), o('Visit the office', 'reasonable_but_unstated'), o('Check a website', 'reasonable_but_unstated')],
      problem: () => 'The office is closed at the moment.',
      problemD: () => [o('The water supply has been cut off.', 'keyword_overlap'), o('The phone line is broken.', 'reasonable_but_unstated'), o('Prices have gone up.', 'reasonable_but_unstated')],
    },
    {
      id: 'new_options',
      setup: () => 'Please note that our menu options have changed.',
      line: () => 'If you are calling about an existing order, pressing two will no longer connect you.',
      why: () => 'To warn callers about a change',
      whyD: () => [o('To announce a new product', 'reasonable_but_unstated'), o('To apologize for a lost order', 'keyword_overlap'), o('To describe the history of the company', 'reasonable_but_unstated')],
      implies: () => 'Callers who use the old option will not reach the right department.',
      impliesD: () => [o('Orders can no longer be placed.', 'keyword_overlap'), o('The menu is the same as before.', 'opposite_meaning'), o('All callers must press two.', 'opposite_meaning')],
      indirect: 2,
      follow: () => 'For orders, please press four instead.',
      request: () => 'To hear these options again, please stay on the line.',
      reqStem: 'How can callers hear the options again?',
      reqAnswer: () => 'By staying on the line',
      reqD: () => [o('By pressing two', 'keyword_overlap'), o('By calling back later', 'reasonable_but_unstated'), o('By visiting a website', 'reasonable_but_unstated')],
      problem: () => 'Some menu options have been reassigned.',
      problemD: () => [o('The company stopped taking orders.', 'reasonable_but_unstated'), o('The office hours were reduced.', 'reasonable_but_unstated'), o('The phone number changed.', 'reasonable_but_unstated')],
    },
  ],
};

// ===========================================================================
const awardSpeech: TalkKit = {
  id: 'award',
  type: 'meeting',
  title: 'Speech',
  instances: [
    { sit: 'events', f: { award: 'Employee of the Year', who: 'our warehouse supervisor', gen: 'an award presentation' }, role: 'A company executive', place: 'At an awards ceremony' },
    { sit: 'events', f: { award: 'the Community Service Award', who: 'our longtime volunteer coordinator', gen: 'an award presentation' }, role: 'An event host', place: 'At a banquet' },
    { sit: 'office', f: { award: 'a retirement celebration', who: 'our head of accounting', gen: 'a retirement celebration' }, role: 'A department manager', place: 'At a company party' },
  ],
  opening: {
    1: [(v) => `Good evening, everyone. Tonight we are here to honor ${v.i.f.who} with ${v.i.f.award}.`],
    2: [(v) => `Good evening. When I was asked to say a few words tonight about ${v.i.f.who}, I didn't hesitate for a second.`],
    3: [(v) => `Good evening, everyone. Twenty years ago, a young woman walked into our office with a résumé and a borrowed suit. Tonight, that same person is ${v.i.f.who}, and we're here because of ${v.i.f.award}.`],
  },
  detail: () => 'During that time, she helped the company open four new locations.',
  detailQ: () => ({ stem: 'According to the speaker, what did the honoree help do?', answer: 'Open new locations', d: [o('Design a product', 'reasonable_but_unstated'), o('Hire a new director', 'reasonable_but_unstated'), o('Reduce costs', 'reasonable_but_unstated')] }),
  purposeStem: 'What is the main purpose of the speech?',
  purpose: () => 'To recognize an employee',
  purposeD: () => [o('To announce new locations', 'true_but_irrelevant'), o('To introduce a job applicant', 'keyword_overlap'), o('To explain a hiring policy', 'reasonable_but_unstated'), o('To launch a fundraising campaign', 'reasonable_but_unstated')],
  roleStem: 'Where most likely is the speech taking place?',
  turns: [
    {
      id: 'never_sick',
      setup: () => 'People often ask me what makes her so special.',
      line: () => "Well, in twenty years, I can't remember a single deadline she missed.",
      why: () => 'To emphasize the honoree\'s reliability',
      whyD: () => [o('To criticize other employees', 'reasonable_but_unstated'), o('To mention a problem with the speaker\'s memory', 'literal_interpretation'), o('To announce a new deadline', 'keyword_overlap')],
      implies: () => 'The honoree is extremely dependable.',
      impliesD: () => [o('The honoree often worked late.', 'reasonable_but_unstated'), o('The speaker forgets deadlines.', 'literal_interpretation'), o('The honoree is new to the company.', 'opposite_meaning')],
      indirect: 2,
      follow: () => 'That kind of dependability is rare.',
      request: () => 'Please join me in raising a glass to her.',
      reqStem: 'What are listeners asked to do?',
      reqAnswer: () => 'Make a toast',
      reqD: () => [o('Take photographs', 'reasonable_but_unstated'), o('Sign a card', 'reasonable_but_unstated'), o('Give a speech', 'reasonable_but_unstated')],
      problem: () => 'Some people wonder what makes the honoree stand out.',
      problemD: () => [o('A deadline was missed.', 'opposite_meaning'), o('The event started late.', 'reasonable_but_unstated'), o('Some guests could not attend.', 'reasonable_but_unstated')],
    },
    {
      id: 'mentor',
      setup: () => "Her work numbers are impressive, but that's not what I'll remember most.",
      line: () => 'Half of the managers in this room were trained by her.',
      why: () => 'To highlight the honoree\'s influence on others',
      whyD: () => [o('To report the number of managers', 'literal_interpretation'), o('To complain about a lack of training', 'opposite_meaning'), o('To introduce the managers', 'reasonable_but_unstated')],
      implies: () => 'The honoree has helped many colleagues develop.',
      impliesD: () => [o('Half of the managers are leaving.', 'reasonable_but_unstated'), o('The honoree is a new manager.', 'opposite_meaning'), o('Managers must attend training.', 'keyword_overlap')],
      indirect: 3,
      follow: () => "I'm one of them, actually.",
      request: () => "Now, let's hear a few words from the woman herself.",
      reqStem: 'What will most likely happen next?',
      reqAnswer: () => 'The honoree will speak.',
      reqD: () => [o('Dinner will be served.', 'reasonable_but_unstated'), o('The managers will be introduced.', 'keyword_overlap'), o('A video will be shown.', 'reasonable_but_unstated')],
      problem: () => 'Numbers alone do not describe the honoree\'s contribution.',
      problemD: () => [o('The honoree\'s numbers were disappointing.', 'opposite_meaning'), o('The speaker forgot the numbers.', 'reasonable_but_unstated'), o('Some managers were not trained.', 'reasonable_but_unstated')],
    },
  ],
};

// ===========================================================================
const trafficWeather: TalkKit = {
  id: 'traffic',
  type: 'broadcast',
  title: 'Broadcast',
  instances: [
    { sit: 'travel', f: { road: 'Harbor Road', gen: 'traffic conditions', alt: 'Station Road' }, role: 'A radio announcer', place: 'On a radio program' },
    { sit: 'travel', f: { road: 'the Kingsley Bridge', gen: 'traffic conditions', alt: 'the Riverside tunnel' }, role: 'A traffic reporter', place: 'On a radio program' },
    { sit: 'events', f: { road: 'Lakeview Avenue', gen: 'a local event and traffic', alt: 'Mill Lane' }, role: 'A radio host', place: 'On a local radio station' },
  ],
  opening: {
    1: [(v) => `This is your five o'clock traffic update. ${v.i.f.road} is closed in both directions this evening.`],
    2: [(v) => `Good evening, drivers. If you're heading downtown in the next hour, you'll want to hear this — there's been a change on ${v.i.f.road}.`],
    3: [(v) => `Good evening. The city marathon wrapped up about an hour ago, but its effects on the roads aren't over yet — especially around ${v.i.f.road}.`],
  },
  detail: () => 'Crews expect to reopen all lanes by nine P.M.',
  detailQ: () => ({ stem: 'When are all lanes expected to reopen?', answer: 'By nine P.M.', d: [o('By five o\'clock', 'wrong_time'), o('Tomorrow morning', 'reasonable_but_unstated'), o('In one hour', 'wrong_time')] }),
  purposeStem: 'What is the broadcast mainly about?',
  purpose: (v) => v.i.f.gen.charAt(0).toUpperCase() + v.i.f.gen.slice(1),
  purposeD: () => [o('A marathon result', 'true_but_irrelevant'), o('A new bus service', 'reasonable_but_unstated'), o('Road construction plans for next year', 'reasonable_but_unstated'), o('A weather warning', 'reasonable_but_unstated')],
  roleStem: 'Who most likely is the speaker?',
  turns: [
    {
      id: 'alt_route',
      setup: () => 'Traffic is already backed up for about two kilometers.',
      line: (v) => `${v.i.f.alt} is moving smoothly right now.`,
      why: () => 'To recommend a different route',
      whyD: (v) => [o(`To report that ${v.i.f.alt} has reopened`, 'reasonable_but_unstated'), o('To describe current road conditions in general', 'literal_interpretation'), o(`To warn drivers about ${v.i.f.alt}`, 'opposite_meaning')],
      implies: (v) => `Drivers should consider using ${v.i.f.alt}.`,
      impliesD: (v) => [o(`${v.i.f.alt} is closed.`, 'opposite_meaning'), o('All roads are congested.', 'opposite_meaning'), o('Drivers should stay home.', 'reasonable_but_unstated')],
      indirect: 2,
      follow: () => 'It adds only a few minutes to most trips.',
      request: () => "We'll have another update at five-thirty.",
      reqStem: 'What will happen at five-thirty?',
      reqAnswer: () => 'Another report will be given.',
      reqD: () => [o('The road will reopen.', 'wrong_time'), o('A race will begin.', 'reasonable_but_unstated'), o('Buses will stop running.', 'reasonable_but_unstated')],
      problem: () => 'A main road is blocked.',
      problemD: () => [o('A bus route has been canceled.', 'reasonable_but_unstated'), o('A bridge is being painted.', 'reasonable_but_unstated'), o('Parking prices have increased.', 'reasonable_but_unstated')],
    },
    {
      id: 'trains',
      setup: () => "If you're thinking about driving downtown tonight, think again.",
      line: () => 'The trains are running every five minutes until midnight.',
      why: () => 'To suggest using public transportation',
      whyD: () => [o('To announce a new train schedule', 'literal_interpretation'), o('To warn about train delays', 'opposite_meaning'), o('To promote a late-night event', 'reasonable_but_unstated')],
      implies: () => 'Taking the train would be a convenient option.',
      impliesD: () => [o('The trains stop at midnight permanently.', 'keyword_overlap'), o('Driving is faster than the train.', 'opposite_meaning'), o('The trains are crowded.', 'reasonable_but_unstated')],
      indirect: 2,
      follow: () => 'And parking at all stations is free this evening.',
      request: () => 'Stay tuned for the weather forecast after this short break.',
      reqStem: 'What will listeners hear next?',
      reqAnswer: () => 'A weather forecast',
      reqD: () => [o('A traffic update', 'keyword_overlap'), o('An interview', 'reasonable_but_unstated'), o('The news headlines', 'reasonable_but_unstated')],
      problem: () => 'Driving downtown will be difficult.',
      problemD: () => [o('Trains are delayed.', 'opposite_meaning'), o('Parking fees have gone up.', 'opposite_meaning'), o('A station is closed.', 'reasonable_but_unstated')],
    },
  ],
};

export const TALKS_B: TalkKit[] = [advertisement, orientation, recorded, awardSpeech, trafficWeather];
