/**
 * TOEIC 900+ vocabulary bank.
 *
 * Each entry has two context frames where ONLY the target fits (near-miss
 * distractors were chosen to be same part of speech but wrong in collocation
 * or meaning for both frames), plus synonyms for paraphrase items.
 * Placeholders: {company} {name} {city} {day} {month}
 */
import type { Difficulty } from '../../domain/types';

export interface VocabEntry {
  word: string;
  pos: 'v' | 'n' | 'adj' | 'adv';
  ko: string;
  /** synonym(s) usable as a paraphrase in BOTH frames */
  syn: string[];
  /** same-POS words that do NOT fit either frame */
  miss: string[];
  frames: [string, string];
  colloc: string[];
  level: Difficulty;
}

export const VOCAB: VocabEntry[] = [
  // ---------------- verbs ----------------
  { word: 'expedite', pos: 'v', ko: '신속히 처리하다', syn: ['speed up', 'accelerate'], miss: ['exceed', 'extend', 'expire'], frames: ['For an additional fee, we can ___ the shipment so that it arrives before {day}.', '{name} asked the bank to ___ the loan approval because the closing date had been moved up.'], colloc: ['expedite the shipment', 'expedite the process'], level: 4 },
  { word: 'implement', pos: 'v', ko: '시행하다', syn: ['put into effect', 'carry out'], miss: ['implicate', 'imply', 'impair'], frames: ['{company} will ___ the new recycling program at all of its branches next quarter.', 'The committee agreed on the changes, but it may take months to ___ them fully.'], colloc: ['implement a policy', 'implement changes'], level: 3 },
  { word: 'accommodate', pos: 'v', ko: '수용하다', syn: ['hold', 'have room for'], miss: ['accumulate', 'accompany', 'acknowledge'], frames: ['The main ballroom can ___ up to 400 guests for a seated dinner.', 'The new parking garage will ___ nearly twice as many vehicles as the old lot.'], colloc: ['accommodate guests', 'accommodate a request'], level: 3 },
  { word: 'allocate', pos: 'v', ko: '할당하다', syn: ['assign', 'set aside'], miss: ['relocate', 'alleviate', 'appeal'], frames: ['The board decided to ___ an additional $50,000 to employee training.', 'Managers must ___ desk space fairly among the incoming interns.'], colloc: ['allocate funds', 'allocate resources'], level: 4 },
  { word: 'alleviate', pos: 'v', ko: '완화하다', syn: ['ease', 'relieve'], miss: ['elevate', 'allocate', 'elaborate'], frames: ['The city built a second bridge to ___ traffic congestion downtown.', 'Hiring two temporary clerks should ___ the pressure on the accounting staff this month.'], colloc: ['alleviate congestion', 'alleviate pressure'], level: 4 },
  { word: 'comply', pos: 'v', ko: '준수하다', syn: ['conform', 'follow the rules'], miss: ['complete', 'compile', 'compete'], frames: ['All vendors must ___ with the updated safety regulations by {month}.', 'Restaurants that fail to ___ with the health code may be fined.'], colloc: ['comply with regulations'], level: 3 },
  { word: 'reimburse', pos: 'v', ko: '상환하다', syn: ['pay back', 'refund'], miss: ['reinforce', 'resume', 'retain'], frames: ['{company} will ___ employees for travel expenses within ten business days.', 'Please keep your receipts so that we can ___ you for the cost of the hotel.'], colloc: ['reimburse expenses', 'reimburse employees'], level: 3 },
  { word: 'postpone', pos: 'v', ko: '연기하다', syn: ['put off', 'delay'], miss: ['propose', 'position', 'pronounce'], frames: ['Because the keynote speaker is ill, we have to ___ the product launch until {month}.', 'The contractor asked us to ___ the inspection by one week.'], colloc: ['postpone a meeting', 'postpone the launch'], level: 2 },
  { word: 'retain', pos: 'v', ko: '유지하다, 보유하다', syn: ['keep', 'hold on to'], miss: ['restrain', 'retire', 'remind'], frames: ['Offering flexible hours has helped {company} ___ experienced staff.', 'Customers should ___ the original receipt for the duration of the warranty.'], colloc: ['retain employees', 'retain a receipt'], level: 3 },
  { word: 'solicit', pos: 'v', ko: '요청하다, 구하다', syn: ['ask for', 'request'], miss: ['solidify', 'resolve', 'suspend'], frames: ['The planning committee will ___ feedback from residents before finalizing the design.', 'The museum plans to ___ donations from local businesses for the new wing.'], colloc: ['solicit feedback', 'solicit donations'], level: 4 },
  { word: 'streamline', pos: 'v', ko: '간소화하다', syn: ['simplify', 'make more efficient'], miss: ['stipulate', 'stretch', 'sustain'], frames: ['The new software will ___ the process of submitting expense reports.', '{name} was hired to ___ the ordering procedures in the warehouse.'], colloc: ['streamline a process'], level: 4 },
  { word: 'oversee', pos: 'v', ko: '감독하다', syn: ['supervise', 'manage'], miss: ['overhear', 'overcome', 'overtake'], frames: ['{name} will ___ the renovation of the {city} branch.', 'A senior engineer was appointed to ___ the installation of the new equipment.'], colloc: ['oversee a project'], level: 3 },
  { word: 'address', pos: 'v', ko: '(문제를) 다루다', syn: ['deal with', 'handle'], miss: ['adopt', 'adhere', 'admit'], frames: ['The next meeting will ___ the complaints about slow delivery times.', 'The manager promised to ___ the staffing shortage before the busy season.'], colloc: ['address a problem', 'address concerns'], level: 4 },
  { word: 'renew', pos: 'v', ko: '갱신하다', syn: ['extend', 'continue'], miss: ['renovate', 'remove', 'reveal'], frames: ['Members who ___ their subscription before {month} receive a 10 percent discount.', 'We decided not to ___ the lease on the downtown office.'], colloc: ['renew a contract', 'renew a subscription'], level: 2 },
  { word: 'verify', pos: 'v', ko: '확인하다, 검증하다', syn: ['confirm', 'check'], miss: ['vary', 'venture', 'value'], frames: ['Please ___ your shipping address before completing the order.', 'The auditors will ___ that all expenses were properly recorded.'], colloc: ['verify an address', 'verify information'], level: 3 },
  { word: 'undergo', pos: 'v', ko: '겪다, 받다', syn: ['go through', 'experience'], miss: ['undertake', 'underline', 'undermine'], frames: ['The east wing of the hospital will ___ extensive renovations this summer.', 'All new pilots must ___ six weeks of simulator training.'], colloc: ['undergo renovations', 'undergo training'], level: 4 },
  { word: 'attribute', pos: 'v', ko: '~의 탓/덕으로 보다', syn: ['credit', 'ascribe'], miss: ['contribute', 'distribute', 'attend'], frames: ['Analysts ___ the rise in profits to lower shipping costs.', 'Many observers ___ the team\'s success to careful planning.'], colloc: ['attribute A to B'], level: 5 },
  { word: 'anticipate', pos: 'v', ko: '예상하다', syn: ['expect', 'predict'], miss: ['participate', 'articulate', 'accelerate'], frames: ['We ___ a significant increase in bookings during the holiday season.', 'Organizers ___ that more than 3,000 people will attend the fair.'], colloc: ['anticipate demand'], level: 3 },
  { word: 'consolidate', pos: 'v', ko: '통합하다', syn: ['combine', 'merge'], miss: ['console', 'consult', 'constitute'], frames: ['{company} plans to ___ its three warehouses into a single facility.', 'The bank helped the client ___ several small loans into one.'], colloc: ['consolidate operations'], level: 4 },
  { word: 'waive', pos: 'v', ko: '면제하다, (권리를) 포기하다', syn: ['cancel', 'drop'], miss: ['wave', 'weigh', 'wage'], frames: ['The hotel agreed to ___ the cancellation fee because of the storm.', 'For members, we ___ the usual delivery charge on orders over $50.'], colloc: ['waive a fee'], level: 4 },
  { word: 'commence', pos: 'v', ko: '시작하다', syn: ['begin', 'start'], miss: ['commend', 'comment', 'commute'], frames: ['Construction of the new terminal will ___ in early {month}.', 'The awards ceremony will ___ at 7 P.M. in the main hall.'], colloc: ['commence operations'], level: 3 },
  { word: 'enclose', pos: 'v', ko: '동봉하다', syn: ['include', 'insert'], miss: ['disclose', 'enforce', 'encounter'], frames: ['Please ___ a copy of your receipt with the returned item.', 'Applicants should ___ two letters of reference with the application form.'], colloc: ['enclose a copy'], level: 3 },
  { word: 'adhere', pos: 'v', ko: '고수하다', syn: ['stick', 'keep'], miss: ['adjourn', 'admire', 'advance'], frames: ['All staff must ___ to the dress code when meeting clients.', 'Contractors are required to ___ to the project timeline.'], colloc: ['adhere to rules'], level: 4 },
  { word: 'procure', pos: 'v', ko: '조달하다', syn: ['obtain', 'acquire'], miss: ['proceed', 'propel', 'prolong'], frames: ['The purchasing team was able to ___ the materials at a lower cost.', 'It took three weeks to ___ enough steel for the project.'], colloc: ['procure materials'], level: 5 },
  { word: 'reconcile', pos: 'v', ko: '(장부를) 맞추다, 조정하다', syn: ['match up', 'balance'], miss: ['recommend', 'recite', 'recover'], frames: ['The accountant must ___ the bank statements with the company records each month.', 'We need to ___ the two sets of figures before the audit.'], colloc: ['reconcile accounts'], level: 5 },

  // ---------------- nouns ----------------
  { word: 'itinerary', pos: 'n', ko: '여행 일정표', syn: ['travel schedule', 'travel plan'], miss: ['inventory', 'invoice', 'inquiry'], frames: ['Your ___ includes a two-night stay in {city} and a guided tour of the harbor.', 'The travel agent e-mailed {name} a revised ___ after the flight was changed.'], colloc: ['travel itinerary'], level: 3 },
  { word: 'inventory', pos: 'n', ko: '재고', syn: ['stock', 'goods on hand'], miss: ['itinerary', 'inquiry', 'invention'], frames: ['The store closes early on {day} so that staff can count the ___.', 'Our ___ of winter coats is running low, so we have placed another order.'], colloc: ['take inventory', 'inventory levels'], level: 2 },
  { word: 'invoice', pos: 'n', ko: '송장, 청구서', syn: ['bill', 'statement of charges'], miss: ['voice', 'venue', 'voucher'], frames: ['Payment is due within 30 days of the date on the ___.', 'The supplier sent an ___ that listed the wrong quantity of paper.'], colloc: ['issue an invoice', 'pay an invoice'], level: 2 },
  { word: 'venue', pos: 'n', ko: '장소', syn: ['location', 'site'], miss: ['revenue', 'avenue', 'value'], frames: ['The ___ for this year\'s conference has not been confirmed yet.', 'We need a larger ___ because more than 500 people have registered.'], colloc: ['event venue'], level: 2 },
  { word: 'revenue', pos: 'n', ko: '수익', syn: ['income', 'earnings'], miss: ['venue', 'revision', 'review'], frames: ['Online sales now account for nearly half of the company\'s ___.', 'Advertising ___ rose by 12 percent in the third quarter.'], colloc: ['generate revenue'], level: 3 },
  { word: 'reimbursement', pos: 'n', ko: '상환, 환급', syn: ['repayment', 'refund'], miss: ['requirement', 'resignation', 'recruitment'], frames: ['Submit your receipts to the finance office to receive ___ for travel costs.', '___ requests without supporting documents will be returned.'], colloc: ['request reimbursement'], level: 3 },
  { word: 'prerequisite', pos: 'n', ko: '전제 조건', syn: ['requirement', 'precondition'], miss: ['perspective', 'prescription', 'preference'], frames: ['Completion of the introductory course is a ___ for the advanced workshop.', 'A valid driver\'s license is a ___ for this delivery position.'], colloc: ['a prerequisite for'], level: 4 },
  { word: 'incentive', pos: 'n', ko: '장려책, 인센티브', syn: ['motivation', 'reward'], miss: ['incident', 'intention', 'inception'], frames: ['The city offers a tax ___ to companies that hire local residents.', 'As an ___, customers who refer a friend receive a free month of service.'], colloc: ['offer an incentive'], level: 3 },
  { word: 'discrepancy', pos: 'n', ko: '불일치', syn: ['difference', 'inconsistency'], miss: ['disposal', 'discretion', 'description'], frames: ['The auditor found a ___ between the invoice and the delivery record.', 'Please report any ___ in your paycheck to the payroll office.'], colloc: ['a discrepancy between'], level: 4 },
  { word: 'tenant', pos: 'n', ko: '세입자', syn: ['renter', 'occupant'], miss: ['tendency', 'tender', 'talent'], frames: ['Every ___ in the building will receive a new parking permit.', 'The landlord notified each ___ that the water would be shut off on {day}.'], colloc: ['commercial tenant'], level: 3 },
  { word: 'patronage', pos: 'n', ko: '(고객의) 애용', syn: ['business', 'support'], miss: ['heritage', 'percentage', 'package'], frames: ['We thank you for your continued ___ over the past ten years.', 'The restaurant rewards customer ___ with a loyalty card.'], colloc: ['thank you for your patronage'], level: 4 },
  { word: 'remittance', pos: 'n', ko: '송금(액)', syn: ['payment', 'money sent'], miss: ['admittance', 'maintenance', 'resistance'], frames: ['Please include the invoice number with your ___.', 'Once we receive your ___, the order will be shipped.'], colloc: ['send remittance'], level: 5 },
  { word: 'feasibility', pos: 'n', ko: '실현 가능성', syn: ['practicality', 'viability'], miss: ['facility', 'familiarity', 'flexibility'], frames: ['Engineers are studying the ___ of building a second runway.', 'Before investing, the board requested a ___ study.'], colloc: ['feasibility study'], level: 4 },
  { word: 'amenity', pos: 'n', ko: '편의 시설', syn: ['facility', 'convenience'], miss: ['amendment', 'ambition', 'attendance'], frames: ['The hotel\'s most popular ___ is the rooftop pool.', 'Tenants can enjoy every ___ of the building, including a shared lounge.'], colloc: ['hotel amenities'], level: 3 },
  { word: 'turnover', pos: 'n', ko: '이직률', syn: ['rate of staff leaving', 'staff replacement rate'], miss: ['takeover', 'overturn', 'handover'], frames: ['High employee ___ has made it difficult to keep experienced staff.', 'The new benefits package is intended to reduce staff ___.'], colloc: ['employee turnover'], level: 4 },
  { word: 'consensus', pos: 'n', ko: '합의', syn: ['agreement', 'general accord'], miss: ['census', 'consent', 'conduct'], frames: ['After a long discussion, the board reached a ___ on the budget.', 'There is a growing ___ among analysts that prices will fall.'], colloc: ['reach a consensus'], level: 4 },
  { word: 'liability', pos: 'n', ko: '(법적) 책임', syn: ['legal responsibility', 'obligation'], miss: ['ability', 'reliability', 'library'], frames: ['The company accepts no ___ for items left in the lockers.', 'The contract limits our ___ in case of delayed delivery.'], colloc: ['accept liability'], level: 5 },
  { word: 'quota', pos: 'n', ko: '할당량', syn: ['target', 'set amount'], miss: ['quote', 'quality', 'quorum'], frames: ['Each sales representative must meet a monthly ___ of 40 new accounts.', 'The factory exceeded its production ___ for the third month in a row.'], colloc: ['meet a quota'], level: 3 },
  { word: 'deadline', pos: 'n', ko: '마감', syn: ['due date', 'time limit'], miss: ['headline', 'skyline', 'outline'], frames: ['The ___ for submitting proposals has been extended to {day}.', 'We worked late to meet the ___ set by the client.'], colloc: ['meet a deadline'], level: 1 },
  { word: 'stipend', pos: 'n', ko: '(정기) 수당, 급료', syn: ['allowance', 'fixed payment'], miss: ['stipulation', 'spending', 'stamina'], frames: ['Interns receive a monthly ___ to cover housing and meals.', 'The fellowship includes a travel ___ of $2,000.'], colloc: ['monthly stipend'], level: 5 },

  // ---------------- adjectives ----------------
  { word: 'tentative', pos: 'adj', ko: '잠정적인', syn: ['provisional', 'not yet final'], miss: ['attentive', 'intensive', 'tedious'], frames: ['We have a ___ agreement, but the final contract has not been signed.', 'The schedule is still ___ and may change before {day}.'], colloc: ['tentative schedule', 'tentative agreement'], level: 4 },
  { word: 'complimentary', pos: 'adj', ko: '무료의', syn: ['free', 'at no charge'], miss: ['complementary', 'comprehensive', 'compulsory'], frames: ['Guests staying three nights or more receive a ___ breakfast.', 'All attendees will be given a ___ tote bag at the registration desk.'], colloc: ['complimentary breakfast'], level: 3 },
  { word: 'mandatory', pos: 'adj', ko: '의무적인', syn: ['required', 'compulsory'], miss: ['momentary', 'monetary', 'migratory'], frames: ['Attendance at the safety briefing is ___ for all factory workers.', 'Wearing a hard hat is ___ in the construction area.'], colloc: ['mandatory training'], level: 3 },
  { word: 'eligible', pos: 'adj', ko: '자격이 있는', syn: ['qualified', 'entitled'], miss: ['legible', 'reliable', 'edible'], frames: ['Employees with one year of service are ___ for the tuition program.', 'Only orders over $100 are ___ for free shipping.'], colloc: ['eligible for'], level: 3 },
  { word: 'preliminary', pos: 'adj', ko: '예비의, 초기의', syn: ['initial', 'early'], miss: ['premium', 'prehistoric', 'permanent'], frames: ['The ___ results of the survey will be shared at the meeting on {day}.', 'We held a ___ discussion before the formal negotiations began.'], colloc: ['preliminary results'], level: 4 },
  { word: 'adjacent', pos: 'adj', ko: '인접한', syn: ['next', 'neighboring'], miss: ['adequate', 'abundant', 'absent'], frames: ['Visitors may park in the lot ___ to the main entrance.', 'The café is ___ to the hotel lobby.'], colloc: ['adjacent to'], level: 4 },
  { word: 'prominent', pos: 'adj', ko: '저명한, 눈에 띄는', syn: ['well-known', 'leading'], miss: ['permanent', 'pertinent', 'prompt'], frames: ['A ___ architect has been hired to design the new library.', 'The conference will feature several ___ economists.'], colloc: ['prominent figure'], level: 4 },
  { word: 'pertinent', pos: 'adj', ko: '관련 있는', syn: ['relevant', 'applicable'], miss: ['persistent', 'prominent', 'permanent'], frames: ['Please bring all ___ documents to your appointment.', 'Only information ___ to the investigation should be included.'], colloc: ['pertinent information'], level: 5 },
  { word: 'obsolete', pos: 'adj', ko: '구식의, 더 이상 쓰이지 않는', syn: ['outdated', 'no longer used'], miss: ['absolute', 'obvious', 'obedient'], frames: ['The old billing software became ___ after the system upgrade.', 'Many of the parts in stock are now ___ and will be recycled.'], colloc: ['become obsolete'], level: 4 },
  { word: 'lucrative', pos: 'adj', ko: '수익성이 좋은', syn: ['profitable', 'well-paying'], miss: ['lucid', 'luxurious', 'literal'], frames: ['The firm won a ___ contract to supply the city\'s buses.', 'Online advertising has become a ___ business for the newspaper.'], colloc: ['lucrative contract'], level: 4 },
  { word: 'reluctant', pos: 'adj', ko: '꺼리는', syn: ['unwilling', 'hesitant'], miss: ['relevant', 'reliant', 'redundant'], frames: ['Many customers are ___ to share personal information online.', 'The board was ___ to approve such a large expense.'], colloc: ['reluctant to'], level: 3 },
  { word: 'imperative', pos: 'adj', ko: '필수적인', syn: ['essential', 'vital'], miss: ['imperial', 'impressive', 'impartial'], frames: ['It is ___ that all passwords be changed before {day}.', 'It is ___ to keep the storage room at a constant temperature.'], colloc: ['it is imperative that'], level: 5 },
  { word: 'versatile', pos: 'adj', ko: '다용도의, 다재다능한', syn: ['adaptable', 'multipurpose'], miss: ['volatile', 'verbal', 'vertical'], frames: ['This ___ printer can scan, copy, and print on both sides.', '{name} is a ___ designer who works in print and digital media.'], colloc: ['versatile tool'], level: 4 },
  { word: 'stringent', pos: 'adj', ko: '엄격한', syn: ['strict', 'rigorous'], miss: ['stagnant', 'strenuous', 'straight'], frames: ['The lab follows ___ safety standards.', 'Food importers must meet ___ inspection requirements.'], colloc: ['stringent standards'], level: 5 },
  { word: 'durable', pos: 'adj', ko: '내구성 있는', syn: ['long-lasting', 'sturdy'], miss: ['desirable', 'divisible', 'dependent'], frames: ['The backpacks are made of a ___ fabric that resists tearing.', 'Customers praised the new flooring as ___ and easy to clean.'], colloc: ['durable material'], level: 3 },
  { word: 'confidential', pos: 'adj', ko: '기밀의', syn: ['private', 'secret'], miss: ['confident', 'congenial', 'considerate'], frames: ['Salary information is ___ and should not be shared.', 'All client files must be kept in a ___ folder.'], colloc: ['confidential information'], level: 3 },
  { word: 'redundant', pos: 'adj', ko: '불필요한, 중복되는', syn: ['unnecessary', 'repetitive'], miss: ['abundant', 'reluctant', 'responsive'], frames: ['The editor removed several ___ sentences from the report.', 'The new system makes the second approval step ___.'], colloc: ['redundant step'], level: 5 },
  { word: 'sustainable', pos: 'adj', ko: '지속 가능한', syn: ['environmentally responsible', 'long-term'], miss: ['susceptible', 'substantial', 'suspicious'], frames: ['{company} uses only ___ materials in its packaging.', 'The city is looking for ___ ways to reduce energy use.'], colloc: ['sustainable materials'], level: 3 },
  { word: 'cordial', pos: 'adj', ko: '다정한, 화기애애한', syn: ['friendly', 'warm'], miss: ['cardinal', 'critical', 'crucial'], frames: ['The two companies have maintained a ___ relationship for years.', 'Despite the disagreement, the meeting remained ___.'], colloc: ['cordial relationship'], level: 5 },
  { word: 'ample', pos: 'adj', ko: '충분한', syn: ['sufficient', 'plentiful'], miss: ['simple', 'apparent', 'amateur'], frames: ['There is ___ parking behind the convention center.', 'Participants will have ___ time to ask questions after the talk.'], colloc: ['ample time', 'ample space'], level: 4 },
  { word: 'rigorous', pos: 'adj', ko: '철저한, 엄격한', syn: ['thorough', 'strict'], miss: ['ravenous', 'humorous', 'generous'], frames: ['Every product goes through ___ testing before it is released.', 'The certification program is known for its ___ exams.'], colloc: ['rigorous testing'], level: 4 },
  { word: 'defective', pos: 'adj', ko: '결함 있는', syn: ['faulty', 'broken'], miss: ['effective', 'defensive', 'decisive'], frames: ['Please return any ___ items within 30 days for a full refund.', 'A ___ part caused the assembly line to stop.'], colloc: ['defective product'], level: 3 },
  { word: 'fragile', pos: 'adj', ko: '깨지기 쉬운', syn: ['breakable', 'delicate'], miss: ['fertile', 'frequent', 'fluent'], frames: ['Please handle the glassware carefully because it is ___.', 'Boxes containing ___ items must be clearly labeled.'], colloc: ['fragile items'], level: 2 },
  { word: 'optimal', pos: 'adj', ko: '최적의', syn: ['best', 'ideal'], miss: ['optional', 'optical', 'original'], frames: ['The plants are kept at the ___ temperature for growth.', 'Our consultants will help you find the ___ layout for your store.'], colloc: ['optimal conditions'], level: 4 },

  // ---------------- adverbs ----------------
  { word: 'promptly', pos: 'adv', ko: '즉시, 정각에', syn: ['immediately', 'without delay'], miss: ['profoundly', 'probably', 'privately'], frames: ['Our staff will ___ respond to any maintenance request.', 'Customer complaints should be answered ___.'], colloc: ['respond promptly', 'promptly at'], level: 2 },
  { word: 'tentatively', pos: 'adv', ko: '잠정적으로', syn: ['provisionally', 'for now'], miss: ['attentively', 'intensively', 'tediously'], frames: ['The grand opening is ___ scheduled for {month} 15.', 'The two firms have ___ agreed to share the cost of the study.'], colloc: ['tentatively scheduled'], level: 4 },
  { word: 'exclusively', pos: 'adv', ko: '독점적으로, 오로지', syn: ['only', 'solely'], miss: ['excessively', 'expensively', 'extensively'], frames: ['These discounts are available ___ to members of the loyalty program.', 'The parking area is reserved ___ for delivery vehicles.'], colloc: ['exclusively for'], level: 4 },
  { word: 'temporarily', pos: 'adv', ko: '일시적으로', syn: ['for a short time', 'briefly'], miss: ['contemporarily', 'permanently', 'tremendously'], frames: ['The elevator is ___ out of service while it is being repaired.', 'The store will be ___ closed for inventory on {day}.'], colloc: ['temporarily closed'], level: 2 },
  { word: 'considerably', pos: 'adv', ko: '상당히', syn: ['significantly', 'substantially'], miss: ['considerately', 'conveniently', 'confidentially'], frames: ['Shipping costs have risen ___ over the past year.', 'The new model is ___ lighter than the old one.'], colloc: ['considerably higher'], level: 4 },
  { word: 'consecutively', pos: 'adv', ko: '연속적으로', syn: ['in a row', 'one after another'], miss: ['consequently', 'considerably', 'conveniently'], frames: ['The store has won the award for three years ___.', 'The workshops will run ___ on {day} and the following day.'], colloc: ['three years consecutively'], level: 5 },
  { word: 'readily', pos: 'adv', ko: '손쉽게, 선뜻', syn: ['easily', 'without difficulty'], miss: ['ready', 'rarely', 'roughly'], frames: ['Replacement parts are ___ available at most hardware stores.', 'Customers can ___ find product information on our website.'], colloc: ['readily available'], level: 4 },
  { word: 'approximately', pos: 'adv', ko: '대략', syn: ['about', 'roughly'], miss: ['appropriately', 'accurately', 'apparently'], frames: ['The tour lasts ___ two hours, including a lunch break.', '___ 300 people attended the product launch.'], colloc: ['approximately two hours'], level: 2 },
  { word: 'periodically', pos: 'adv', ko: '주기적으로', syn: ['regularly', 'from time to time'], miss: ['particularly', 'partially', 'politely'], frames: ['The equipment is ___ inspected to ensure it meets safety standards.', 'Please check the website ___ for updates to the schedule.'], colloc: ['periodically inspected'], level: 3 },

  // ---------------- additional 990-level entries ----------------
  { word: 'defer', pos: 'v', ko: '미루다, 연기하다', syn: ['delay', 'put off'], miss: ['defeat', 'deflect', 'define'], frames: ['The committee agreed to ___ the vote until all members could attend.', 'Customers may ___ payment for up to ninety days at no extra cost.'], colloc: ['defer payment', 'defer a decision'], level: 4 },
  { word: 'forfeit', pos: 'v', ko: '몰수당하다, 잃다', syn: ['lose', 'give up'], miss: ['forge', 'foresee', 'fortify'], frames: ['Guests who cancel less than 24 hours in advance will ___ their deposit.', 'Employees who do not use their vacation days by {month} ___ them.'], colloc: ['forfeit a deposit'], level: 5 },
  { word: 'mediate', pos: 'v', ko: '중재하다', syn: ['negotiate between', 'settle'], miss: ['meditate', 'medicate', 'motivate'], frames: ['An outside consultant was hired to ___ the dispute between the two suppliers.', '{name} offered to ___ between the landlord and the tenants.'], colloc: ['mediate a dispute'], level: 5 },
  { word: 'outsource', pos: 'v', ko: '외주를 주다', syn: ['contract out', 'subcontract'], miss: ['outnumber', 'outline', 'outlast'], frames: ['{company} decided to ___ its payroll processing to a specialist firm.', 'Many small businesses ___ their IT support to reduce costs.'], colloc: ['outsource production'], level: 3 },
  { word: 'replenish', pos: 'v', ko: '보충하다', syn: ['restock', 'refill'], miss: ['replace', 'relinquish', 'reprimand'], frames: ['Staff ___ the shelves every morning before the store opens.', 'We need to ___ our supply of printer ink before the audit.'], colloc: ['replenish stock'], level: 4 },
  { word: 'surpass', pos: 'v', ko: '능가하다, 넘어서다', syn: ['exceed', 'go beyond'], miss: ['surround', 'surrender', 'suppress'], frames: ['Sales this quarter are expected to ___ last year\'s record.', 'The number of online orders may soon ___ in-store purchases.'], colloc: ['surpass expectations'], level: 4 },
  { word: 'endorse', pos: 'v', ko: '지지하다, 보증하다', syn: ['support', 'approve'], miss: ['enforce', 'endure', 'enclose'], frames: ['Several well-known athletes ___ the new line of running shoes.', 'The board voted to ___ the proposal for a four-day workweek.'], colloc: ['endorse a product'], level: 4 },
  { word: 'expire', pos: 'v', ko: '만료되다', syn: ['end', 'run out'], miss: ['inspire', 'aspire', 'expand'], frames: ['Your parking permit will ___ at the end of {month}.', 'The discount code will ___ if it is not used within a week.'], colloc: ['a contract expires'], level: 2 },
  { word: 'launch', pos: 'v', ko: '출시하다, 시작하다', syn: ['introduce', 'start'], miss: ['lunch', 'lounge', 'lend'], frames: ['{company} will ___ its new mobile app next {month}.', 'The city plans to ___ a campaign to promote recycling.'], colloc: ['launch a product'], level: 1 },
  { word: 'relinquish', pos: 'v', ko: '(권리·지위를) 내주다', syn: ['give up', 'hand over'], miss: ['replenish', 'relish', 'reinforce'], frames: ['The founder agreed to ___ control of the company to the new board.', '{name} will ___ the role of chair after ten years.'], colloc: ['relinquish control'], level: 5 },
  { word: 'itemize', pos: 'v', ko: '항목별로 적다', syn: ['list individually', 'break down'], miss: ['idolize', 'immunize', 'utilize'], frames: ['Please ___ all expenses on the reimbursement form.', 'The contractor will ___ the cost of labor and materials in the quote.'], colloc: ['itemize expenses'], level: 4 },
  { word: 'clarify', pos: 'v', ko: '명확히 하다', syn: ['explain', 'make clear'], miss: ['classify', 'glorify', 'certify'], frames: ['Could you ___ the payment terms before we sign?', 'The manager sent an e-mail to ___ the new vacation policy.'], colloc: ['clarify a point'], level: 2 },
  { word: 'provision', pos: 'n', ko: '(계약) 조항, 공급', syn: ['clause', 'condition'], miss: ['provocation', 'proposition', 'profession'], frames: ['A ___ in the contract allows either party to cancel with thirty days\' notice.', 'The lease includes a ___ for annual rent increases.'], colloc: ['a provision in the contract'], level: 4 },
  { word: 'shortfall', pos: 'n', ko: '부족분', syn: ['deficit', 'shortage'], miss: ['downfall', 'windfall', 'shortcut'], frames: ['The department is facing a budget ___ of about $20,000.', 'A ___ in donations forced the museum to reduce its hours.'], colloc: ['budget shortfall'], level: 4 },
  { word: 'backlog', pos: 'n', ko: '밀린 일, 적체', syn: ['accumulation of work', 'pile of pending tasks'], miss: ['blog', 'backup', 'background'], frames: ['The new clerks helped clear a ___ of insurance claims.', 'Because of the holidays, there is a ___ of orders waiting to be shipped.'], colloc: ['a backlog of orders'], level: 4 },
  { word: 'commission', pos: 'n', ko: '수수료, 커미션', syn: ['fee', 'percentage paid'], miss: ['omission', 'admission', 'permission'], frames: ['Sales staff earn a ___ of five percent on every car they sell.', 'The agency charges a ___ for each apartment it rents out.'], colloc: ['earn a commission'], level: 3 },
  { word: 'overhead', pos: 'n', ko: '간접비, 운영비', syn: ['operating costs', 'running expenses'], miss: ['overhaul', 'overtime', 'overview'], frames: ['Moving to a smaller office will reduce our ___.', 'Rent and utilities make up most of the store\'s ___.'], colloc: ['reduce overhead'], level: 4 },
  { word: 'retention', pos: 'n', ko: '유지, 보유', syn: ['keeping', 'holding on'], miss: ['attention', 'retirement', 'retraction'], frames: ['The bonus program has improved employee ___.', 'Customer ___ rose after the loyalty app was introduced.'], colloc: ['employee retention'], level: 4 },
  { word: 'stipulation', pos: 'n', ko: '(계약상) 조건', syn: ['requirement', 'condition'], miss: ['stimulation', 'speculation', 'stimulus'], frames: ['The grant was awarded with the ___ that results be published.', 'One ___ of the sale is that the current staff keep their jobs.'], colloc: ['with the stipulation that'], level: 5 },
  { word: 'proximity', pos: 'n', ko: '근접성', syn: ['nearness', 'closeness'], miss: ['prosperity', 'probability', 'priority'], frames: ['The hotel is popular because of its ___ to the convention center.', 'Buyers value the building\'s ___ to public transportation.'], colloc: ['proximity to'], level: 4 },
  { word: 'turnout', pos: 'n', ko: '참가자 수', syn: ['attendance', 'number of people attending'], miss: ['turnover', 'outlet', 'output'], frames: ['___ at this year\'s job fair was the highest ever.', 'Organizers were pleased with the ___ despite the rain.'], colloc: ['high turnout'], level: 3 },
  { word: 'aptitude', pos: 'n', ko: '적성, 소질', syn: ['talent', 'natural ability'], miss: ['attitude', 'altitude', 'amplitude'], frames: ['Applicants must take an ___ test before the interview.', '{name} showed a clear ___ for financial analysis.'], colloc: ['aptitude test'], level: 4 },
  { word: 'lenient', pos: 'adj', ko: '관대한', syn: ['flexible', 'tolerant'], miss: ['legible', 'luminous', 'latent'], frames: ['The library has a ___ policy on late returns.', 'Some airlines are more ___ about carry-on baggage size than others.'], colloc: ['lenient policy'], level: 5 },
  { word: 'feasible', pos: 'adj', ko: '실현 가능한', syn: ['practical', 'workable'], miss: ['festive', 'flexible', 'fearful'], frames: ['Engineers say it is ___ to finish the bridge by spring.', 'The consultant proposed a more ___ timeline.'], colloc: ['technically feasible'], level: 4 },
  { word: 'interim', pos: 'adj', ko: '임시의, 중간의', syn: ['temporary', 'provisional'], miss: ['internal', 'intimate', 'inferior'], frames: ['{name} will serve as ___ director until a replacement is found.', 'The auditors submitted an ___ report in {month}.'], colloc: ['interim manager'], level: 4 },
  { word: 'unanimous', pos: 'adj', ko: '만장일치의', syn: ['agreed by everyone', 'undivided'], miss: ['anonymous', 'unanswered', 'uniform'], frames: ['The board reached a ___ decision to approve the merger.', 'The proposal received ___ support from the committee.'], colloc: ['unanimous decision'], level: 4 },
  { word: 'meticulous', pos: 'adj', ko: '꼼꼼한', syn: ['very careful', 'precise'], miss: ['miraculous', 'meteoric', 'mischievous'], frames: ['{name} is known for keeping ___ records of every transaction.', 'The restoration required ___ attention to detail.'], colloc: ['meticulous records'], level: 5 },
  { word: 'reputable', pos: 'adj', ko: '평판이 좋은', syn: ['respected', 'trustworthy'], miss: ['repeatable', 'refundable', 'removable'], frames: ['We only work with ___ suppliers who meet our standards.', 'Please hire a ___ contractor for the roof repairs.'], colloc: ['reputable company'], level: 4 },
  { word: 'vacant', pos: 'adj', ko: '비어 있는', syn: ['empty', 'unoccupied'], miss: ['vague', 'valid', 'vast'], frames: ['The ___ office on the third floor will become a meeting room.', 'There are two ___ positions in the accounting department.'], colloc: ['vacant position'], level: 3 },
  { word: 'prospective', pos: 'adj', ko: '장래의, 잠재적인', syn: ['potential', 'future'], miss: ['perspective', 'productive', 'protective'], frames: ['We will give ___ clients a tour of the factory on {day}.', 'All ___ employees must complete a background check.'], colloc: ['prospective client'], level: 4 },
  { word: 'concise', pos: 'adj', ko: '간결한', syn: ['brief', 'short and clear'], miss: ['precise', 'concave', 'consecutive'], frames: ['Please keep your summary ___ — no more than one page.', 'The manual gives ___ instructions for each step.'], colloc: ['concise summary'], level: 3 },
  { word: 'substantially', pos: 'adv', ko: '상당히', syn: ['considerably', 'significantly'], miss: ['substitutionally', 'subsequently', 'subjectively'], frames: ['The renovation ___ increased the value of the property.', 'Our energy bills have fallen ___ since the solar panels were installed.'], colloc: ['substantially increase'], level: 4 },
  { word: 'subsequently', pos: 'adv', ko: '그 후에', syn: ['afterward', 'later'], miss: ['substantially', 'consequentially', 'frequently'], frames: ['The product was tested in {city} and ___ launched nationwide.', '{name} joined as an intern and was ___ hired full-time.'], colloc: ['subsequently approved'], level: 4 },
];

export const VOCAB_BY_WORD: Record<string, VocabEntry> = Object.fromEntries(VOCAB.map((v) => [v.word, v]));
